plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.4'
	id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '17'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Spring core
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-mail' // ✅ para envío de emails

	// Utilidades
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	// Base de datos
	runtimeOnly 'com.mysql:mysql-connector-j'

	// PDF y Excel
	implementation 'org.apache.poi:poi-ooxml:5.2.5'
	implementation 'com.lowagie:itext:2.1.7'

	// MercadoPago
	implementation('com.mercadopago:sdk-java:2.1.24') {
		exclude group: 'org.sonatype.sisu', module: 'sisu-guice'
	}

	// Auditoría
	implementation 'org.hibernate.orm:hibernate-envers:6.4.4.Final'

	// Testing
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}
